trigger:
  - main  

pool:
  name: ubuntuagent  

variables:
  - group: aks-backend-kv-group  #  Pulling ARM_ACCESS_KEY from Key Vault

 # Backend configuration variables
  - name: backend_resource_group
    value: "tfstate-backend-aksrg"
  - name: backend_storage_account
    value: "tfstatebackenddanish"
  - name: backend_container_name
    value: "tfstate"
  - name: backend_key
    value: "aks-cluster.terraform.tfstate"

steps:
  - task: TerraformInstaller@1
    displayName: "Install Terraform"
    inputs:
      terraformVersion: '1.6.6' 

  - script: |
      terraform init \
        -backend-config="resource_group_name=$(backend_resource_group)" \
        -backend-config="storage_account_name=$(backend_storage_account)" \
        -backend-config="container_name=$(backend_container_name)" \
        -backend-config="key=$(backend_key)"
    displayName: "Terraform Init"
    env:
      ARM_ACCESS_KEY: $(ARM-ACCESS-KEY)

  - script: |
      terraform plan -out=tfplan
    displayName: "Terraform Plan"
    env:
      ARM_ACCESS_KEY: $(ARM-ACCESS-KEY)

  - script: |
      terraform apply -auto-approve tfplan
    displayName: "Terraform Apply"
    env:
      ARM_ACCESS_KEY: $(ARM-ACCESS-KEY)